/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_chalmers_fleetspeak_audio_codec_opus_jniopus_OpusEncoderWrapper */

#ifndef _Included_se_chalmers_fleetspeak_audio_codec_opus_jniopus_OpusEncoderWrapper
#define _Included_se_chalmers_fleetspeak_audio_codec_opus_jniopus_OpusEncoderWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_chalmers_fleetspeak_audio_codec_opus_jniopus_OpusEncoderWrapper
 * Method:    getSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_se_chalmers_fleetspeak_audio_codec_opus_jniopus_OpusEncoderWrapper_getSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     se_chalmers_fleetspeak_audio_codec_opus_jniopus_OpusEncoderWrapper
 * Method:    create
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_se_chalmers_fleetspeak_audio_codec_opus_jniopus_OpusEncoderWrapper_create
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     se_chalmers_fleetspeak_audio_codec_opus_jniopus_OpusEncoderWrapper
 * Method:    encode
 * Signature: (J[BII[BII)I
 */
JNIEXPORT jint JNICALL Java_se_chalmers_fleetspeak_audio_codec_opus_jniopus_OpusEncoderWrapper_encode
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     se_chalmers_fleetspeak_audio_codec_opus_jniopus_OpusEncoderWrapper
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_se_chalmers_fleetspeak_audio_codec_opus_jniopus_OpusEncoderWrapper_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     se_chalmers_fleetspeak_audio_codec_opus_jniopus_OpusEncoderWrapper
 * Method:    ctl
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_se_chalmers_fleetspeak_audio_codec_opus_jniopus_OpusEncoderWrapper_ctl
        (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
