/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_chalmers_fleetspeak_sound_OpusEncoder */

#ifndef _Included_se_chalmers_fleetspeak_sound_OpusEncoder
#define _Included_se_chalmers_fleetspeak_sound_OpusEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_chalmers_fleetspeak_sound_OpusEncoder
 * Method:    opus_encoder_create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_se_chalmers_fleetspeak_sound_OpusEncoder_opus_1encoder_1create
  (JNIEnv *, jclass);

/*
 * Class:     se_chalmers_fleetspeak_sound_OpusEncoder
 * Method:    opus_encoder_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_se_chalmers_fleetspeak_sound_OpusEncoder_opus_1encoder_1destroy
  (JNIEnv *, jclass);

/*
 * Class:     se_chalmers_fleetspeak_sound_OpusEncoder
 * Method:    getSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_se_chalmers_fleetspeak_sound_OpusEncoder_getSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     se_chalmers_fleetspeak_sound_OpusEncoder
 * Method:    encode
 * Signature: (F)S
 */
JNIEXPORT jshort JNICALL Java_se_chalmers_fleetspeak_sound_OpusEncoder_encode
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     se_chalmers_fleetspeak_sound_OpusEncoder
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_se_chalmers_fleetspeak_sound_OpusEncoder_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
