/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_chalmers_fleetspeak_jni_OpusEncoder */

#ifndef _Included_se_chalmers_fleetspeak_jni_OpusEncoder
#define _Included_se_chalmers_fleetspeak_jni_OpusEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_chalmers_fleetspeak_jni_OpusEncoder
 * Method:    getSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_se_chalmers_fleetspeak_jni_OpusEncoder_getSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     se_chalmers_fleetspeak_jni_OpusEncoder
 * Method:    create
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_se_chalmers_fleetspeak_jni_OpusEncoder_create
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     se_chalmers_fleetspeak_jni_OpusEncoder
 * Method:    encode
 * Signature: (J[BII[BII)I
 */
JNIEXPORT jint JNICALL Java_se_chalmers_fleetspeak_jni_OpusEncoder_encode
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     se_chalmers_fleetspeak_jni_OpusEncoder
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_se_chalmers_fleetspeak_jni_OpusEncoder_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     se_chalmers_fleetspeak_jni_OpusEncoder
 * Method:    ctl
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_se_chalmers_fleetspeak_jni_OpusEncoder_ctl
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
